name: Trigger Colab Training

on:
  schedule:
    - cron: "0 */6 * * *"   # Run every 6 hours
  workflow_dispatch:       # allow manual trigger from GitHub UI

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Google Apps Script (Colab autorun)
        run: |
          curl -X POST "https://script.google.com/macros/s/AKfycbz1qBSdkbr4dQYL974myOeLec0nCkN6ups31iJsiJo4emBr4vRbhSZkZKHDarJpZp5OUA/exec"
